// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialPublisherWorker.Infrastructure.Persistence;

#nullable disable

namespace SocialPublisherWorker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530145959_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("SocialPublisherWorker.Domain.Entities.PostPublication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalPostId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Platform")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "WeekStart")
                        .IsUnique();

                    b.ToTable("PostPublications");
                });
#pragma warning restore 612, 618
        }
    }
}
